get_patterns = {
    "get_table": [
        {
            "prefix": "Show my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves a table of data.",
        },
        {
            "prefix": "List all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists all records in a table.",
        },
        {
            "prefix": "Get all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches all entries from a specified table.",
        },
        {
            "prefix": "Fetch my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches a table of data specific to the user.",
        },
        {
            "prefix": "Fetch all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves all records from a table.",
        },
        {
            "prefix": "Show ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern displays a table of data.",
        },
        {
            "prefix": "Send my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends a table of data specific to the user.",
        },
        {
            "prefix": "Send me ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends a table of data to the user.",
        },
        {
            "prefix": "Show me ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows a table of data to the user.",
        },
        {
            "prefix": "Send all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends all records from a table.",
        },
        {
            "prefix": "Show all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows all records from a table.",
        },
        {
            "prefix": "List ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists records from a table.",
        },
        {
            "prefix": "Get ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves records from a table.",
        },
    ],
    "get_detail": [
        {
            "prefix": "Show my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "List all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists all records in a table.",
        },
        {
            "prefix": "Get all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches all entries from a specified table.",
        },
        {
            "prefix": "Fetch my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches detailed information specific to the user.",
        },
        {
            "prefix": "Fetch all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves all records from a table.",
        },
        {
            "prefix": "Show ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows detailed information from a table.",
        },
        {
            "prefix": "Send my ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information specific to the user.",
        },
        {
            "prefix": "Send me ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information to the user.",
        },
        {
            "prefix": "Show me ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "Send all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends all records from a table.",
        },
        {
            "prefix": "Show all ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows all records from a table.",
        },
        {
            "prefix": "List ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists records from a table.",
        },
        {
            "prefix": "Get ",
            "suffix": "",
            "intent": "GET",
            "output_format": "DETAIL",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves a single record from a table.",
        },
    ],
    "show_top": [
        {
            "prefix": "Show top {N} ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f""""This pattern retrieves the top N records from a table, 
            where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.""",
        },
        {
            "prefix": "Show latest {N} ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f"This pattern retrieves the latest N records from a table, where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.",
        },
        {
            "prefix": "Show recent {N} ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f"This pattern retrieves the most recent N records from a table, where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.",
        },
        {
            "prefix": "Show first {N} ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f"This pattern retrieves the first N records from a table, where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.",
        },
        {
            "prefix": "Show next {N} ",
            "suffix": "",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f"This pattern retrieves the next N records from a table, where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.",
        },
        {
            "prefix": "Show {N} ",
            "suffix": " random",
            "intent": "GET",
            "output_format": "TABLE",
            "limit": "{N}",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": f"This pattern retrieves N random records from a table, where N is a variable number specified in the query. like 1, 2, 5, 10, 20, etc.",
        },
    ],
    "get_card": [
        {
            "prefix": "Show my ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "List all ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists all records in a table.",
        },
        {
            "prefix": "Get all ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches all entries from a specified table.",
        },
        {
            "prefix": "Fetch my ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches detailed information specific to the user.",
        },
        {
            "prefix": "Fetch all ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves all records from a table.",
        },
        {
            "prefix": "Show ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows detailed information from a table.",
        },
        {
            "prefix": "Send my ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information specific to the user.",
        },
        {
            "prefix": "Send me ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information to the user.",
        },
        {
            "prefix": "Show me ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "Send all ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends all records from a table.",
        },
        {
            "prefix": "Show all ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows all records from a table.",
        },
        {
            "prefix": "List ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists records from a table.",
        },
        {
            "prefix": "Get ",
            "suffix": "in card format",
            "intent": "GET",
            "output_format": "CARD",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves a single record from a table.",
        },
    ],
    "get_bullet": [
        {
            "prefix": "Show my ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "List all ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists all records in a table.",
        },
        {
            "prefix": "Get all ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches all entries from a specified table.",
        },
        {
            "prefix": "Fetch my ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches detailed information specific to the user.",
        },
        {
            "prefix": "Fetch all ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves all records from a table.",
        },
        {
            "prefix": "Show ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows detailed information from a table.",
        },
        {
            "prefix": "Send my ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information specific to the user.",
        },
        {
            "prefix": "Send me ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends detailed information to the user.",
        },
        {
            "prefix": "Show me ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "Send all ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern sends all records from a table.",
        },
        {
            "prefix": "Show all ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows all records from a table.",
        },
        {
            "prefix": "List ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "10",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern lists records from a table.",
        },
        {
            "prefix": "Get ",
            "suffix": "in bullet points",
            "intent": "GET",
            "output_format": "BULLET",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves a single record from a table.",
        },
    ],
    "get_summarized": [
        {
            "prefix": "Show my ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern retrieves detailed information specific to the user.",
        },
        {
            "prefix": "Fetch my ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern fetches detailed information specific to the user.",
        },
        {
            "prefix": "Show ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "This pattern shows detailed information from a table.",
        },
        {
            "prefix": "Send my ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Send me ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Show me ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Get ",
            "suffix": "in summarized view",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
           "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Summarize my ",
            "suffix": "",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Explain my ",
            "suffix": "",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
        {
            "prefix": "Explain this ",
            "suffix": "",
            "intent": "SUMMARIZE",
            "output_format": "SUMMARIZED",
            "limit": "1",
            "is_field": False,
            "filters": [{"field": {}, "operator": "EQUAL", "value": "user"}],
            "order_field": {},
            "order_direction": "ASC",
            "group_by_fields": [],
            "docstring": "The filter ensures that the data retrieved is specific to the user. This pattern retrieves a single record from a table. the filter field should be dynamic based on the user context.",
        },
    ],
}
