OBJECT_SYNONYMS = {
    "Activity": [
        "activities",
        "task",
        "tasks",
        "meeting",
        "meetings",
        "event",
        "events",
        "appointment",
        "appointments",
        "call",
        "calls",
        "follow-up",
        "action",
        "work item",
    ],
    "Leads": [
        "lead",
        "prospect",
        "prospects",
        "potential customer",
        "potential client",
        "opportunity lead",
        "inquiry",
        "new contact",
        "sales lead",
    ],
    "Accounts": [
        "account",
        "customer",
        "customers",
        "client",
        "clients",
        "organization",
        "company",
        "business",
        "partner",
        "enterprise",
        "firm",
    ],
    "Opportunities": [
        "opportunity",
        "opportunities",
        "deal",
        "deals",
        "pipeline",
        "sales chance",
        "prospective sale",
        "sales opportunity",
        "bid",
        "quote",
        "proposal",
    ],
    "Cases": [
        "case",
        "cases",
        "ticket",
        "tickets",
        "issue",
        "issues",
        "complaint",
        "complaints",
        "incident",
        "problem",
        "support request",
        "service request",
    ],
    
    "Survey": ["questionnaire", "feedback form", "poll", "evaluation", "research form"],
    "Notes": ["memo", "remark", "comment", "annotation", "observation", "journal"],
    "Contacts": [
        "person",
        "individual",
        "client",
        "customer",
        "lead contact",
        "prospect",
    ],
    
    "Solutions": ["answer", "fix", "knowledgebase", "resolution", "guide", "how-to"],
    "MarketingCampaign": [
        "promotion",
        "ad campaign",
        "sales drive",
        "outreach",
        "marketing effort",
    ],
    "MailingLists": [
        "subscriber list",
        "distribution list",
        "email list",
        "contacts group",
    ],
    "Alerts": ["notification", "warning", "reminder", "alert message", "trigger"],
    "IssueRequirementMaster": [
        "requirement",
        "specification",
        "business need",
        "demand",
    ],
    "Competitors": [
        "rival",
        "challenger",
        "market competitor",
        "opponent",
        "other vendor",
    ],
    "OpportunityPartners": ["deal partners", "associated partner", "sales partner"],
    "Queue": ["line", "task queue", "waiting list", "pipeline"],
    "OpportunityContacts": ["deal contact", "associated person", "linked contact"],
    "TemplateMaster": ["template", "blueprint", "format", "document template"],
    "Usercontact": [
        "employee contact",
        "staff contact",
        "user profile",
        "internal contact",
    ],
    "Az_Role": ["role", "permission group", "security role", "access group"],
    "Regions": ["territory", "area", "zone", "geography", "location"],
    "Products": ["item", "goods", "service", "merchandise", "offering"],
    "Teams": ["group", "squad", "department", "crew", "unit"],
    "Forecast": ["projection", "prediction", "estimate", "sales forecast", "plan"],
    "Rpt_Query": ["report query", "analytics request", "data fetch", "report builder"],
    "CustomFieldSchema": [
        "custom fields",
        "user-defined field",
        "extra attribute",
        "schema",
    ],
    "DMSMaster": ["document management", "file repository", "doc system"],
    "ConfigureAlerts": ["alert setup", "notification settings", "trigger config"],
    "Contracts": ["agreement", "deal", "legal document", "commitment"],
    "PriceBooks": ["catalog", "rate card", "pricing list", "tariff"],
    "Payments": ["transaction", "remittance", "settlement", "invoice payment"],
    "Password": ["credential", "key", "login code", "auth password"],
    "QuotaMaster": ["quota", "target", "sales target", "allocation"],
    "UILayoutMaster": ["layout", "screen design", "UI template", "form design"],
    "Quote": ["proposal", "offer", "estimate", "sales quote"],
    "Asset": ["property", "resource", "equipment", "inventory item"],
    "EmailSyndication": ["email campaign", "email blast", "newsletter", "bulk email"],
    "DSB_Master": ["dashboard", "report view", "analytics panel"],
    "Summary": ["overview", "highlight", "abstract", "report summary"],
    "PulsePost": ["social post", "status update", "feed item", "post", "announcement"],
    "Products": ["item", "goods", "service", "merchandise", "offering"],
    "CallScript": ["call guide", "telecalling script", "sales script", "phone script"],
    "CallScriptResult": [
        "call outcome",
        "call response",
        "result of call",
        "script result",
    ],
    "AttachmentMaster": ["document", "file", "upload", "attachment", "record file"],
    "Offers": ["promotion", "discount", "deal", "special offer", "scheme"],
    "CustomActionButton": [
        "shortcut button",
        "quick action",
        "custom button",
        "action trigger",
    ],
    "Locations": ["place", "site", "branch", "address", "area"],
    "Training": ["course", "session", "learning", "education", "coaching"],
    "Module": ["component", "section", "unit", "subsystem", "functionality"],
    "OpportunityLocations": ["deal location", "site of opportunity", "branch for deal"],
    "ObjectSolution": ["solution object", "fix entity", "problem resolution"],
    "Budgets": ["financial plan", "allocation", "funding", "budget sheet"],
    "Expenses": ["spending", "cost", "expenditure", "charges", "outgoings"],
    "Feedback": ["review", "response", "comment", "evaluation", "opinion"],
    "Feedback": ["review", "response", "comment", "evaluation", "opinion"],
    "Workspace": ["dashboard", "work area", "collaboration space", "project space"],
    "Content": ["material", "document", "article", "information", "media"],
    "Warehouse": ["storage", "inventory center", "depot", "facility"],
    "Orders": ["purchase", "request", "sales order", "transaction", "buy request"],
    "ConversationMaster": ["chat", "discussion", "thread", "dialogue", "interaction"],
    "Geography": ["region", "location", "territory", "area", "zone"],
    "Process": ["workflow", "operation", "procedure", "method", "business process"],
    "GeographyMapping": ["territory mapping", "region assignment", "location mapping"],
    "MailingListMembers": [
        "subscribers",
        "contacts in list",
        "email members",
        "distribution members",
    ],
    "CampaignParticipant": [
        "campaign member",
        "participant",
        "attendee",
        "campaign contact",
    ],
    "Reorderpoint": ["restock level", "inventory threshold", "minimum stock"],
    "ObjectProduct": ["product object", "item record", "goods entity"],
    "CallScriptQuestions": ["script prompts", "call questions", "questionnaire"],
    "CallScriptAnswers": ["script responses", "call answers", "customer replies"],
    "Approval": ["authorization", "acceptance", "sanction", "sign-off"],
    "PortFolio": ["investment portfolio", "asset collection", "product mix"],
    "Wealth": ["assets", "capital", "financial holdings", "resources"],
    "Calendar": ["schedule", "planner", "agenda", "timeline"],
    "EventCalendar": ["event schedule", "event planner", "event timeline"],
    "Dlplogging": ["data logging", "DLP log", "tracking log"],
    "Dispatch": ["shipment", "delivery", "sending", "logistics"],
    "Schemes": ["plans", "offers", "programs", "initiatives"],
    "Charge": ["fee", "cost", "expense", "billing"],
    "Attendance": ["presence", "check-in", "roll call", "participation"],
    "Courier": ["delivery service", "parcel", "messenger", "carrier"],
    "Project": ["initiative", "assignment", "workstream", "undertaking"],
    "flow.ScreenFlowView": ["screen workflow", "UI flow", "screen process"],
    "Members": ["users", "participants", "group members", "team"],
    "ForecastModelDefinition": [
        "prediction model",
        "forecast setup",
        "model definition",
    ],
    "Target": ["goal", "objective", "aim", "quota"],
    "Planning": ["preparation", "strategy", "scheduling", "roadmap"],
    "Achievement": ["milestone", "success", "accomplishment", "result"],
    "Review": ["evaluation", "assessment", "feedback", "inspection"],
    "Build": ["version", "release", "deployment", "construct"],
    "Timesheet": ["work log", "time tracking", "hours report", "work hours"],
    "StockAudit": ["inventory check", "stock verification", "audit"],
    "Pool": ["resource pool", "collection", "group", "shared resource"],
    "TestCase": ["scenario", "QA test", "validation case", "test script"],
    "Factor": ["element", "component", "variable", "parameter"],
    "Step": ["Stage", "Phase", "Milestone", "Checkpoint", "Level"],
    "Application": ["App", "Software", "Form", "Program", "System"],
    "flow.AutoFlowView": ["Automated Flow", "Workflow", "Auto Process", "Process Flow"],
    "flow.BusinessProcessFlowView": [
        "Business Flow",
        "Process Pipeline",
        "BPF",
        "Business Workflow",
    ],
    "flow.flowview": ["Flow View", "Process View", "Workflow View", "Flow Diagram"],
    "eKYC": [
        "Electronic KYC",
        "Digital Verification",
        "Identity Check",
        "Customer Verification",
    ],
    "Delight": ["Satisfaction", "Happiness", "Joy", "Customer Delight", "Engagement"],
    "ConversationMaster": ["Chat", "Talk", "Discussion", "Dialogue", "Thread"],
    "Pattern": ["Template", "Format", "Structure", "Design", "Blueprint"],
    "Plans": ["Strategy", "Blueprint", "Schedule", "Roadmap", "Scheme"],
    "QualityCheck": ["QC", "Inspection", "Validation", "Testing", "Audit"],
    "flow.CampaignFlowView": [
        "Campaign Workflow",
        "Marketing Flow",
        "Promotion Process",
    ],
    "Privilege": ["Rights", "Permission", "Access Control", "Authorization"],
    "Liability": ["Debt", "Obligation", "Dues", "Responsibility"],
    "AlertCategory": ["Alert Group", "Notification Type", "Warning Category"],
    "AlertSubCategory": ["Sub Alert Type", "Alert Detail", "Warning Subclass"],
    "App_Master": ["App Metadata", "Application Master", "Software Catalog"],
    "TellerTransaction": [
        "Bank Transaction",
        "Cashier Transaction",
        "Branch Transaction",
        "Deposit/Withdrawal",
    ],
    "SmartControls": ["Dynamic Controls", "Intelligent UI", "Adaptive Elements"],
    "AnalyticsExplorer": [
        "Data Explorer",
        "Report Explorer",
        "Insights Viewer",
        "BI Tool",
    ],
    "SmartCalculator": ["Advanced Calculator", "AI Calculator", "Math Engine"],
    "LeaderboardConsole": [
        "Ranking Board",
        "Scoreboard",
        "Gamification Board",
        "Performance Chart",
    ],
    "Sanction": ["Approval", "Authorization", "Permit", "Endorsement"],
    "Deviation": ["Variance", "Exception", "Drift", "Irregularity"],
    "Subsidiary": ["Child Company", "Branch", "Unit", "Division"],
    "Verification": ["Validation", "Authentication", "Check", "Review"],
    "Feature": ["Capability", "Function", "Attribute", "Characteristic"],
    "Holding": ["Ownership", "Shareholding", "Possession", "Portfolio"],
    "Service": ["Support", "Assistance", "Offering", "Utility"],
    "HouseHold": ["Family", "Residence", "Home Unit", "House"],
    "Prediction": ["Forecast", "Estimation", "Projection", "Anticipation"],
    "Splits": ["Division", "Separation", "Partition", "Breakdown"],
    "Journey": ["Path", "Process", "Lifecycle", "Workflow"],
    "Credit": ["Loan", "Finance", "Borrowing", "Credit Line"],
    "Facility": ["Service Center", "Branch", "Unit", "Amenity"],
    "Security": ["Safety", "Protection", "Defense", "Safeguard"],
    "Revenue": ["Income", "Earnings", "Sales", "Turnover"],
    "ChannelPartner": ["Distributor", "Reseller", "Dealer", "Affiliate"],
    "AgendaMaster": ["Meeting Agenda", "Schedule", "Plan", "Program"],
    "ObjectBank": ["Bank Object", "Financial Entity", "Bank Record"],
    "Risk": ["Threat", "Exposure", "Hazard", "Uncertainty"],
    "ReleaseMaster": ["Version Release", "Deployment", "Launch"],
    "BalanceSheet": ["Financial Statement", "Accounts", "Ledger"],
    "Package": ["Bundle", "Kit", "Set", "Offering"],
    "Relationship": ["Connection", "Association", "Link", "Bond"],
    "Workunit": ["Task Unit", "Job Block", "Execution Unit"],
    "Program": ["Initiative", "Project", "Plan", "Campaign"],
    "Audience": ["Viewers", "Users", "Participants", "Customers"],
    "Segment": ["Group", "Category", "Cluster", "Division"],
    "DataSource": ["Database", "Input Source", "Repository", "Feed"],
    "QueryBuilder": ["SQL Builder", "Search Constructor", "Query Tool"],
    "Employee": ["Staff", "Worker", "Team Member", "Personnel"],
    "Candidate": ["Applicant", "Prospect", "Nominee", "Job Seeker"],
    "Campaign": ["Promotion", "Drive", "Initiative", "Outreach"],
    "Workflow": ["Process", "Pipeline", "Automation", "Operation"],
    "LoyaltyProgram": ["Rewards Program", "Points System", "Customer Loyalty"],
    "Knowledge": ["Information", "Wisdom", "Data", "Insights"],
    "Channel": ["Medium", "Pathway", "Distribution", "Network"],
    "Game": ["Play", "Match", "Contest", "Competition"],
    "Agent": ["Assistant", "Bot", "Representative", "Handler"],
    "Portal": ["Gateway", "Dashboard", "Access Point", "Hub"],
    "Migration": ["Transfer", "Transition", "Move", "Upgrade"],
    "PriceList": ["Rate Card", "Tariff", "Catalog", "Pricing Sheet"],
}


def get_synonyms(object_name):
    return OBJECT_SYNONYMS.get(object_name, [])
