get_summary_pattern_dict = {
    # GET Patterns
    "Show my {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "List all {ObjectPlural}": {
        "intent": "GET",
        "output_format": "LiST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} assigned to me": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} created this week": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} created this month": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "List {ObjectPlural} by status": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show top {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show recent {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show Last {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show upcoming {ObjectPlural}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show completed {ObjectPlural}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show pending {ObjectPlural}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show my priority {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show my overdue {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show my high priority {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show my medium priority {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show my low priority {ObjectPlural}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show 1 {Object} record": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show 5 {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show next {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show first {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show last {N} {ObjectPlural}": {
        "intent": "GET",
        "output_format": "CARD",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {N} {ObjectPlural} sorted by {Field}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {N} {ObjectPlural} filtered by {Field} = {Value}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {N} {ObjectPlural} grouped by {Field}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Find {ObjectPlural} by {Field}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Search {ObjectPlural} where {Field} = {Value}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Search for {Object} with {Field} = {Value}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Look up {Object} by {Field}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Search {ObjectPlural} containing {Keyword}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },

    # SUMMARY Patterns
    "Summarize my {Object}": {
        "intent": "SUMMARY",
        "output_format": "TEXT",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Summarize {Object}": {
        "intent": "SUMMARY",
        "output_format": "TEXT",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Give me a summary of Given {Object} id": {
        "intent": "SUMMARY",
        "output_format": "TEXT",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show summarized {ObjectPlural}": {
        "intent": "SUMMARY",
        "output_format": "TEXT",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} report": {
        "intent": "SUMMARY",
        "output_format": "GRAPH",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} trends over time": {
        "intent": "SUMMARY",
        "output_format": "GRAPH",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} in bullet list view": {
        "intent": "SUMMARY",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": [],
    },
    "Show {ObjectPlural} in description view": {
        "intent": "SUMMARY",
        "output_format": "TEXT",
        "primary_object": "{Object}",
        "related_objects": [],
    }
}


get_base_patterns = [
    "Show my {ObjectPlural}",
    "List all {ObjectPlural}",
    "Show {ObjectPlural} assigned to me",
    "Show {ObjectPlural} created this week",
    "Show {ObjectPlural} created this month",
    "List {ObjectPlural} by status",
    "Show top {N} {ObjectPlural}",
    "Show recent {N} {ObjectPlural}",
    "Show Last {N} {ObjectPlural}",
    "Show upcoming {ObjectPlural}",
    "Show completed {ObjectPlural}",
    "Show pending {ObjectPlural}",
    "show my priority {ObjectPlural}",
    "Show my overdue {ObjectPlural}",
    "Show my high priority {ObjectPlural}",
    "Show my medium priority {ObjectPlural}",
    "Show my low priority {ObjectPlural}",
    "Show 1 {Object} record",
    "Show 5 {ObjectPlural}",
    "Show top {N} {ObjectPlural}",
    "Show recent {N} {ObjectPlural}",
    "Show next {N} {ObjectPlural}",
    "Show first {N} {ObjectPlural}",
    "Show last {N} {ObjectPlural}",
    "Show {N} {ObjectPlural} sorted by {Field}",
    "Show {N} {ObjectPlural} filtered by {Field} = {Value}",
    "Show {N} {ObjectPlural} grouped by {Field}",
    "Find {ObjectPlural} by {Field}",
    "Search {ObjectPlural} where {Field} = {Value}",
    "Search for {Object} with {Field} = {Value}",
    "Look up {Object} by {Field}",
    "Search {ObjectPlural} containing {Keyword}",
    "Find {ObjectPlural} created by {UserName}",
    "Find {ObjectPlural} updated by {UserName}",
    "Search {ObjectPlural} by multiple fields",
    "Search {ObjectPlural} with condition {Field} = {Value}",
    "Find {ObjectPlural} for {Object}",
    "Show {ObjectPlural} where {Field} = {Value}",
    "Show {ObjectPlural} where {Field} contains {Value}",
    "Show {ObjectPlural} where {Field} starts with {Value}",
    "Show {ObjectPlural} where {Field} ends with {Value}",
    "Show {ObjectPlural} created between {Date1} and {Date2}",
    "Show {ObjectPlural} updated after {Date}",
    "Show {ObjectPlural} with status = {Status}",
    "Show {ObjectPlural} owned by me",
    "Show {ObjectPlural} assigned to {UserName}",
    "Show {ObjectPlural} by priority = {High/Medium/Low}",
    "Summarize my {Object}",
    "Summarize {Object}",
    "Give me a summary of Given {Object} id",
    "Show summarized {ObjectPlural}",
    "Show {ObjectPlural} report",
]

related_base_patterns_dict_structured = {
    "Show {ObjectPlural} related to {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "List {ObjectPlural} linked to {RelatedObject}": {
        "intent": "GET",
        "output_format": "TABLE",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "Show {ObjectPlural} connected to {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "Show {ObjectPlural} under {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "Show {ObjectPlural} associated with {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "Show {ObjectPlural} which is related to {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
    "Show {ObjectPlural} which are related to {RelatedObject}": {
        "intent": "GET",
        "output_format": "LIST",
        "primary_object": "{Object}",
        "related_objects": ["{RelatedObject}"],
    },
}

get_base_pattern_by_object = [
    "Show me the detail of {Object}",
    "Get details of {Object}",
    "Show full detail of {Object}",
    "Show {Object} information",
    "Show one {Object} record",
    "Get detailed view of {Object}",
    "Show {Object} fields",
    "Show complete information of {Object}",
    "Summarize my {Object}",
    "Summarize {Object}",
]

related_base_patterns = [
    "Show {ObjectPlural} related to {RelatedObject}",
    "List {ObjectPlural} linked to {RelatedObject}",
    "Show {ObjectPlural} connected to {RelatedObject}",
    "Show {ObjectPlural} under {RelatedObject}",
    "Show {ObjectPlural} associated with {RelatedObject}",
    "Show {ObjectPlural} which is related to {RelatedObject}",
    "Show {ObjectPlural} which are related to {RelatedObject}",
]

in_patterns = [
    "in card view",
    "in card format",
    "in grid view",
    "in table format",
    "in graph view",
    "in chart",
    "in List View",
    "in Bullet List View",
    "in Description View",
    "in proffessional view",
    "in summary view",
    "in Sumarize view",
]

in_patterns_dict = {
    "in card view": "CARD",
    "in card format": "CARD",
    "in grid view": "TABLE",
    "in table format": "TABLE",
    "in graph view": "GRAPH",
    "in chart": "GRAPH",
    "in List View": "LIST",
    "in Description View": "TEXT",
    "in proffessional view": "PROFESSIONAL_TEXT",
    "in summary view": "SUMMARY_TEXT",
    "in Sumarize view": "SUMMARY_TEXT",
}
in_top_n_patterns = range(1, 10)  # Generates numbers from 1 to 10

get_query_pattern_by_object = {
    "list_view": [
        "Show my {ObjectPlural}",
        "List all {ObjectPlural}",
        "Show {ObjectPlural} assigned to me",
        "Show {ObjectPlural} created this week",
        "Show {ObjectPlural} created this month",
        "List {ObjectPlural} by status",
        "Show top {N} {ObjectPlural}",
        "Show recent {N} {ObjectPlural}",
        "Show {ObjectPlural} sorted by {Field}",
        "Show {ObjectPlural} filtered by {Field} = {Value}",
    ],
    "detail_view": [
        "Show me the detail of {Object}",
        "Get details of {Object}",
        "Show full detail of {Object}",
        "Show {Object} information",
        "Show record {RecordID} of {Object}",
        "Show one {Object} record",
        "Get detailed view of {Object}",
        "Show {Object} fields",
        "Show {Object} by {Field}",
        "Show complete information of {Object}",
    ],
    "card_grid_view": [
        "Show {ObjectPlural} in card view",
        "Display {ObjectPlural} in card format",
        "Show {ObjectPlural} in grid view",
        "Display {ObjectPlural} in table format",
        "Show {ObjectPlural} in dashboard view",
        "Show {ObjectPlural} as tiles",
        "Show {ObjectPlural} in Kanban view",
        "Show {ObjectPlural} in compact cards",
        "Show {ObjectPlural} as visual cards",
        "Display {ObjectPlural} as list of cards",
    ],
    "graph_chart_view": [
        "Show {ObjectPlural} in graph view",
        "Display {ObjectPlural} in chart",
        "Show {ObjectPlural} statistics in chart",
        "Compare {ObjectPlural} by {Field} in graph",
        "Show {ObjectPlural} trend by {Field}",
        "Show {ObjectPlural} grouped by {Field} in chart",
        "Display {ObjectPlural} as pie chart",
        "Display {ObjectPlural} as bar chart",
        "Show {ObjectPlural} performance graph",
        "Show {ObjectPlural} summary in graph view",
    ],
    "pagination_n_records": [
        "Show 1 {Object} record",
        "Show 5 {ObjectPlural}",
        "Show top {N} {ObjectPlural}",
        "Show recent {N} {ObjectPlural}",
        "Show next {N} {ObjectPlural}",
        "Show first {N} {ObjectPlural}",
        "Show last {N} {ObjectPlural}",
        "Show {N} {ObjectPlural} sorted by {Field}",
        "Show {N} {ObjectPlural} filtered by {Field} = {Value}",
        "Show {N} {ObjectPlural} grouped by {Field}",
    ],
    "summarize": [
        "Summarize {ObjectPlural}",
        "Give me a summary of {ObjectPlural}",
        "Show summarized {ObjectPlural}",
        "Show {ObjectPlural} report",
        "Show {ObjectPlural} insights",
        "Show total {ObjectPlural} count",
        "Show {ObjectPlural} summary by {Field}",
        "Show {ObjectPlural} aggregated by {Field}",
        "Summarize {ObjectPlural} performance",
        "Summarize {ObjectPlural} by region/status/type",
    ],
    "related_objects": [
        "Show {ObjectPlural} related to {OtherObject}",
        "List {ObjectPlural} linked to {OtherObject}",
        "Show {ObjectPlural} connected to {OtherObject}",
        "Show {ObjectPlural} for {OtherObject} = {Value}",
        "Show {ObjectPlural} under {OtherObject}",
        "Show {ObjectPlural} associated with {OtherObject}",
        "List {ObjectPlural} for account {AccountName}",
        "Show {ObjectPlural} for lead {LeadName}",
        "Show {ObjectPlural} connected to opportunity {OpportunityName}",
        "Show {ObjectPlural} related to case {CaseID}",
    ],
    "filters_conditions": [
        "Show {ObjectPlural} where {Field} = {Value}",
        "Show {ObjectPlural} where {Field} contains {Value}",
        "Show {ObjectPlural} where {Field} starts with {Value}",
        "Show {ObjectPlural} where {Field} ends with {Value}",
        "Show {ObjectPlural} created between {Date1} and {Date2}",
        "Show {ObjectPlural} updated after {Date}",
        "Show {ObjectPlural} with status = {Status}",
        "Show {ObjectPlural} owned by me",
        "Show {ObjectPlural} assigned to {UserName}",
        "Show {ObjectPlural} by priority = {High/Medium/Low}",
    ],
    "search_find": [
        "Find {ObjectPlural} by {Field}",
        "Search {ObjectPlural} where {Field} = {Value}",
        "Search for {Object} with {Field} = {Value}",
        "Look up {Object} by {Field}",
        "Search {ObjectPlural} containing {Keyword}",
        "Find {ObjectPlural} created by {UserName}",
        "Find {ObjectPlural} updated by {UserName}",
        "Search {ObjectPlural} by multiple fields",
        "Search {ObjectPlural} with condition {Field} = {Value}",
        "Find {ObjectPlural} for {OtherObject}",
    ],
    "misc_advanced": [
        "Show overdue {ObjectPlural}",
        "Show upcoming {ObjectPlural}",
        "Show completed {ObjectPlural}",
        "Show pending {ObjectPlural}",
        "Show {ObjectPlural} grouped by {Field}",
        "Show {ObjectPlural} by {Field} in descending order",
        "Show {ObjectPlural} by {Field} in ascending order",
        "Compare {ObjectPlural} by {Field}",
        "Show {ObjectPlural} trends over time",
        "Show {ObjectPlural} count by {Field}",
    ],
}
